// <auto-generated />
using Cocoa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cocoa.Data.Migrations
{
    [DbContext(typeof(CocoaContext))]
    [Migration("20190329175200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Cocoa.Data.Models.Joint", b =>
                {
                    b.Property<int>("JointId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Angle");

                    b.Property<int>("Duration");

                    b.Property<int>("PoseId");

                    b.Property<int>("ServoId");

                    b.HasKey("JointId");

                    b.HasIndex("PoseId");

                    b.ToTable("Joints");
                });

            modelBuilder.Entity("Cocoa.Data.Models.Pose", b =>
                {
                    b.Property<int>("PoseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Delay");

                    b.Property<string>("Name");

                    b.HasKey("PoseId");

                    b.ToTable("Poses");
                });

            modelBuilder.Entity("Cocoa.Data.Models.Sequence", b =>
                {
                    b.Property<int>("SequenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("SequenceId");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("Cocoa.Data.Models.SequencePose", b =>
                {
                    b.Property<int>("SequencePoseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Order");

                    b.Property<int>("PoseId");

                    b.Property<int>("SequenceId");

                    b.HasKey("SequencePoseId");

                    b.HasIndex("PoseId");

                    b.HasIndex("SequenceId");

                    b.ToTable("SequencePoses");
                });

            modelBuilder.Entity("Cocoa.Data.Models.Joint", b =>
                {
                    b.HasOne("Cocoa.Data.Models.Pose")
                        .WithMany("Joints")
                        .HasForeignKey("PoseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cocoa.Data.Models.SequencePose", b =>
                {
                    b.HasOne("Cocoa.Data.Models.Pose", "Pose")
                        .WithMany()
                        .HasForeignKey("PoseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cocoa.Data.Models.Sequence", "Sequence")
                        .WithMany("SequencePoses")
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
